// GENERATED by scripts/sync-amenities.mjs from barkfind-app-v1 src/lib/locationTypeData.ts
// (app commit 9865bbb). Do not edit by hand: change the app, then run the script again.
export const AMENITY_SOURCE = {"file":"barkfind-app-v1/src/lib/locationTypeData.ts","commit":"9865bbb"};
export const CATEGORY_GROUP: Record<string, string> = {
  "pub": "pub-cafe-bar",
  "cafe": "pub-cafe-bar",
  "bar": "pub-cafe-bar",
  "restaurant": "pub-cafe-bar",
  "park": "park-beach",
  "beach": "park-beach",
  "pet-store": "pet-store-vet-groomer",
  "vet": "pet-store-vet-groomer",
  "groomer": "pet-store-vet-groomer"
};
export const AMENITY_GROUPS: Record<string, { title: string; items: { code: string; label: string; tooltip: string }[] }[]> = {
  "pub-cafe-bar": [
    {
      "title": "Water & Food",
      "items": [
        {
          "code": "water-bowls",
          "label": "Water bowls",
          "tooltip": "Fresh water available"
        },
        {
          "code": "treats",
          "label": "Treats",
          "tooltip": "Complimentary or purchasable treats"
        },
        {
          "code": "dedicated-dog-menu",
          "label": "Dog menu",
          "tooltip": "Paid meals or snacks for dogs"
        },
        {
          "code": "puppuccinos",
          "label": "Puppuccinos",
          "tooltip": "Whipped cream/dairy-free treats"
        }
      ]
    },
    {
      "title": "Comfort & Setup",
      "items": [
        {
          "code": "lead-hooks",
          "label": "Lead hooks",
          "tooltip": "Attached to tables/walls"
        },
        {
          "code": "dog-beds-mats",
          "label": "Dog beds",
          "tooltip": "Provided by the venue"
        },
        {
          "code": "blankets",
          "label": "Blankets",
          "tooltip": "To keep dogs cosy or protect furniture"
        },
        {
          "code": "heaters",
          "label": "Heaters",
          "tooltip": "Outdoor heaters for winter visits"
        }
      ]
    },
    {
      "title": "Space & Access",
      "items": [
        {
          "code": "indoor-dog-zone",
          "label": "Indoor dog zone",
          "tooltip": "Allowed inside the main building"
        },
        {
          "code": "on-site-parking",
          "label": "On-site parking",
          "tooltip": "Dedicated parking on premises"
        },
        {
          "code": "street-parking",
          "label": "Street parking",
          "tooltip": "Available street parking nearby"
        }
      ]
    },
    {
      "title": "Hygiene & Safety",
      "items": [
        {
          "code": "waste-bags",
          "label": "Waste bags",
          "tooltip": "Waste bags provided"
        },
        {
          "code": "non-slip-flooring",
          "label": "Non-slip floors",
          "tooltip": "Safe for older/clumsy dogs"
        },
        {
          "code": "cleaning-kit",
          "label": "Cleaning kit",
          "tooltip": "Available for accidents"
        }
      ]
    }
  ],
  "park-beach": [
    {
      "title": "Water & Food",
      "items": [
        {
          "code": "freshwater-taps",
          "label": "Freshwater taps",
          "tooltip": "Taps for drinking water"
        },
        {
          "code": "self-service-stations",
          "label": "Self-service stations",
          "tooltip": "Water stations for dogs"
        }
      ]
    },
    {
      "title": "Comfort & Setup",
      "items": [
        {
          "code": "shaded-areas",
          "label": "Shaded areas",
          "tooltip": "Shelter from sun"
        },
        {
          "code": "benches",
          "label": "Benches",
          "tooltip": "Seating for owners"
        },
        {
          "code": "wash-down-hose",
          "label": "Wash-down hose",
          "tooltip": "Hose for muddy dogs"
        }
      ]
    },
    {
      "title": "Space & Access",
      "items": [
        {
          "code": "fenced-area",
          "label": "Fenced area",
          "tooltip": "Enclosed safe space"
        },
        {
          "code": "off-lead-area",
          "label": "Off-lead",
          "tooltip": "Designated off-lead area"
        },
        {
          "code": "dedicated-car-park",
          "label": "Dedicated car park",
          "tooltip": "Car park at location"
        },
        {
          "code": "trailhead-parking",
          "label": "Trailhead parking",
          "tooltip": "Parking at trail start"
        }
      ]
    },
    {
      "title": "Hygiene & Safety",
      "items": [
        {
          "code": "waste-bins",
          "label": "Waste bins",
          "tooltip": "Bins for dog waste"
        },
        {
          "code": "bag-dispensers",
          "label": "Bag dispensers",
          "tooltip": "Free waste bag dispensers"
        },
        {
          "code": "lighting",
          "label": "Lighting",
          "tooltip": "Well-lit paths and areas"
        }
      ]
    }
  ],
  "pet-store-vet-groomer": [
    {
      "title": "Water & Food",
      "items": [
        {
          "code": "water-station",
          "label": "Water station",
          "tooltip": "Fresh water available"
        },
        {
          "code": "trial-treats",
          "label": "Trial treats",
          "tooltip": "Sample treats for dogs"
        },
        {
          "code": "calming-chews",
          "label": "Calming chews",
          "tooltip": "Anxiety-reducing chews"
        }
      ]
    },
    {
      "title": "Comfort & Setup",
      "items": [
        {
          "code": "holding-areas",
          "label": "Holding areas",
          "tooltip": "Secure holding spaces"
        },
        {
          "code": "cooling-mats",
          "label": "Cooling mats",
          "tooltip": "For hot days"
        },
        {
          "code": "pheromones",
          "label": "Pheromones",
          "tooltip": "Calming pheromone diffusers"
        }
      ]
    },
    {
      "title": "Space & Access",
      "items": [
        {
          "code": "drop-off-vet-bays",
          "label": "Drop-off/vet bays",
          "tooltip": "Dedicated drop-off areas"
        },
        {
          "code": "viewing-area",
          "label": "Viewing area",
          "tooltip": "Watch your pet during grooming"
        },
        {
          "code": "separation-screens",
          "label": "Separation screens",
          "tooltip": "Visual barriers between pets"
        }
      ]
    },
    {
      "title": "Hygiene & Safety",
      "items": [
        {
          "code": "sanitizer",
          "label": "Sanitizer",
          "tooltip": "Hand sanitizer available"
        },
        {
          "code": "tool-sterilization",
          "label": "Tool sterilization",
          "tooltip": "Sterilized grooming tools"
        },
        {
          "code": "double-gated-entry",
          "label": "Double-gated entry",
          "tooltip": "Prevents escape"
        }
      ]
    }
  ]
};
export const AMENITY_CODES: readonly string[] = ["water-bowls","treats","dedicated-dog-menu","puppuccinos","lead-hooks","dog-beds-mats","blankets","heaters","indoor-dog-zone","on-site-parking","street-parking","waste-bags","non-slip-flooring","cleaning-kit","freshwater-taps","self-service-stations","shaded-areas","benches","wash-down-hose","fenced-area","off-lead-area","dedicated-car-park","trailhead-parking","waste-bins","bag-dispensers","lighting","water-station","trial-treats","calming-chews","holding-areas","cooling-mats","pheromones","drop-off-vet-bays","viewing-area","separation-screens","sanitizer","tool-sterilization","double-gated-entry"];
