// Writes rolled-back restore tests, one block per trash item, using exactly the SQL that
// trash_restore runs (api/_lib/hq-trash-plans.ts). Each block runs inside a DO block that
// always ends by raising an exception, so Postgres rolls everything back; the exception
// message carries the result. A final ROLLBACK follows each block as a second guard.
// The column lists come from the live schema (the COLS_SQL query in hq-trash-plans.ts, saved
// as JSON), exactly as trash_restore reads them at restore time.
//   node scripts/trash-restore-tests.ts cols.json <id>:<entity>:<label> ... > docs/hq-trash-restore-tests.sql
import fs from 'node:fs';
import { planFor } from '../api/_lib/hq-trash-plans.ts';

const [colsFile, ...args] = process.argv.slice(2);
const cols = JSON.parse(fs.readFileSync(colsFile, 'utf8'));
const items = args.map((a) => { const [id, entity, ...label] = a.split(':'); return { id, entity, label: label.join(':') }; });
const q = (s: string) => '$q$' + s + '$q$';
const out: string[] = [
  '-- HQ Trash: rolled-back restore tests, generated by scripts/trash-restore-tests.ts from api/_lib/hq-trash-plans.ts.',
  '-- Each block restores one real trash item exactly as HQ would, reports what happened, then rolls back.',
  '-- The DO block always ends with RAISE EXCEPTION: that is what undoes it. Read the result in the error message:',
  '--   "RESULT (rolled back): {...}"   the restore worked; nothing was kept.',
  '--   "REFUSED (rolled back): ..."    HQ would refuse this restore, with this reason.',
  '-- Any other error is a real failure: please send it back.',
  '',
];
items.forEach((it, i) => {
  const plan = planFor(it.entity, cols);
  if (!plan) throw new Error('no plan for ' + it.entity);
  const lines = [
    `-- ${i + 1}. ${it.label} (${it.entity}, trash id ${it.id})`,
    'begin;',
    'set local session_replication_role = replica;',
    'do $test$',
    'declare',
    `  tid uuid := '${it.id}';`,
    '  problem text; n bigint; out jsonb := \'{}\'::jsonb; v jsonb;',
    'begin',
    "  if current_setting('session_replication_role') <> 'replica' then raise exception 'NOT RUN: triggers are still on'; end if;",
    ...plan.checks.flatMap((s) => [
      `  -- check: ${s.label}`,
      `  execute ${q(s.sql)} into problem using tid;`,
      `  if problem is not null then raise exception 'REFUSED (rolled back): %', problem; end if;`,
    ]),
    ...[...plan.steps, ...plan.after].flatMap((s) => [
      `  -- step: ${s.label}`,
      `  execute ${q(s.sql)} using tid;`,
      `  get diagnostics n = row_count; out := out || jsonb_build_object(${JSON.stringify(s.label).replace(/^"|"$/g, "'")}, n);`,
    ]),
    `  execute ${q(plan.verify)} into v using tid;`,
    "  raise exception 'RESULT (rolled back): %', jsonb_build_object('rows', out, 'after', v);",
    'end $test$;',
    'rollback;',
    '',
  ];
  out.push(...lines);
});
process.stdout.write(out.join('\n'));
